# Generated by Django 4.2.7 on 2023-11-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deactivate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
