# Generated by Django 4.2.7 on 2023-11-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
