# Generated by Django 4.2.7 on 2023-11-18 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attachments', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('deadline_type', models.CharField(choices=[('date_time_deadline', 'Data e Hora Marcada'), ('hours_deadline', 'Prazo em Horas'), ('scheduled_date', 'Agendamento para uma Data')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('date_time_deadline', models.DateTimeField(blank=True, null=True)),
                ('hours_deadline', models.IntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('observation', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.ManyToManyField(blank=True, related_name='attachment', to='attachments.attachment')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attended', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.clientmodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='services.type')),
            ],
        ),
    ]
