# Generated by Django 4.2.7 on 2023-11-18 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('document', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telephone1', models.CharField(max_length=15)),
                ('telephone2', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_country', to='core.country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_gender', to='core.gender')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_state', to='core.state')),
            ],
        ),
    ]
